# Generated by Django 4.0.6 on 2022-07-12 17:30

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepage',
            name='earnings',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TeamPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('created_at', models.DateTimeField(verbose_name='Post date')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='Last updated')),
                ('abbr', models.CharField(blank=True, max_length=50)),
                ('earnings', models.PositiveIntegerField(blank=True, null=True)),
                ('team_info', wagtail.fields.StreamField([('section_settings', wagtail.blocks.StructBlock([('key_name', wagtail.blocks.CharBlock(required=False)), ('key_value', wagtail.blocks.CharBlock(required=False)), ('key_url', wagtail.blocks.CharBlock(required=False))]))], use_json_field=True)),
                ('intro', models.CharField(max_length=250)),
                ('hometown', models.CharField(blank=True, max_length=150)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_avatar', to='wagtailimages.image')),
                ('in_game_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_leader', to='profiles.profilepage')),
                ('team_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamcountry', to='profiles.country')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=150)),
                ('url', models.URLField(blank=True, null=True)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_icon', to='wagtailimages.image')),
                ('profile', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_social', to='profiles.profilepage')),
                ('team', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_social', to='profiles.teampage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profilepage',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_team', to='profiles.teampage'),
        ),
    ]
