# Generated by Django 4.0.6 on 2022-07-12 17:33

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profilepage_earnings_teampage_socialmedia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='profile',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_social', to='profiles.profilepage'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='team',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_social', to='profiles.teampage'),
        ),
    ]
