# Generated by Django 4.0.6 on 2022-07-13 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('profiles', '0004_teamindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepage',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_cover', to='wagtailimages.image'),
        ),
    ]
