# Generated by Django 4.0.6 on 2022-07-13 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('profiles', '0006_profilepage_player_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepage',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='profilepage',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
    ]
