# Generated by Django 4.0.6 on 2022-07-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profilepage_player_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepage',
            name='players_characters',
        ),
    ]
