# Generated by Django 4.0.6 on 2022-07-13 17:48

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_profilepage_players_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepage',
            name='intro',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='settingsmain',
            name='profile_settings',
            field=wagtail.fields.StreamField([('section_settings', wagtail.blocks.StructBlock([('sub_heading', wagtail.blocks.CharBlock(required=False)), ('section_details', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('key_name', wagtail.blocks.CharBlock(required=False)), ('value_name', wagtail.blocks.CharBlock(required=False))])))]))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='settingsmain',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
