# Generated by Django 4.0.6 on 2022-07-13 17:54

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_profilepage_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teampage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
