# Generated by Django 4.0.6 on 2022-07-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_profilepage_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='name',
        ),
    ]
