# Generated by Django 4.0.6 on 2022-07-14 11:04

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_alter_profilepage_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teampage',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Post date'),
        ),
        migrations.AlterField(
            model_name='teampage',
            name='team_info',
            field=wagtail.fields.StreamField([('section_settings', wagtail.blocks.StructBlock([('key_name', wagtail.blocks.CharBlock(required=False)), ('key_value', wagtail.blocks.CharBlock(required=False)), ('key_url', wagtail.blocks.CharBlock(required=False))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='teampage',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last updated'),
        ),
        migrations.DeleteModel(
            name='TeamIndexPage',
        ),
    ]
