# Generated by Django 4.0.6 on 2022-07-19 14:32

from django.db import migrations
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_remove_newsindexpage_page_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepage',
            name='text',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock(table_options={'autoColumnSize': True, 'contextMenu': ['mergeCells', 'row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'undo', 'redo', '---------', 'copy', 'cut---------', 'alignment'], 'mergeCells': True}))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='profilepage',
            name='text',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock(table_options={'autoColumnSize': True, 'contextMenu': ['mergeCells', 'row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'undo', 'redo', '---------', 'copy', 'cut---------', 'alignment'], 'mergeCells': True}))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='teampage',
            name='text',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock(table_options={'autoColumnSize': True, 'contextMenu': ['mergeCells', 'row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'undo', 'redo', '---------', 'copy', 'cut---------', 'alignment'], 'mergeCells': True}))], blank=True, null=True, use_json_field=True),
        ),
    ]
