# Generated by Django 4.0.6 on 2022-07-19 17:04

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_gamepage_text_profilepage_text_teampage_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepage',
            name='related_profiles',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='profiles.profilepage'),
        ),
    ]
