# Generated by Django 4.0.6 on 2022-07-21 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_profilepage_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SettingsMain',
        ),
    ]
