# Generated by Django 4.0.6 on 2022-07-21 14:11

from django.db import migrations
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_delete_settingsmain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepage',
            name='settings',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock(table_options={'autoColumnSize': True, 'contextMenu': ['mergeCells', 'row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'undo', 'redo', '---------', 'copy', 'cut---------', 'alignment'], 'mergeCells': True}))], blank=True, null=True, use_json_field=True),
        ),
    ]
