# Generated by Django 4.0.6 on 2022-07-21 15:37

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.table_block.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('profiles', '0024_alter_profilepage_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='profilepage',
            name='settings',
            field=wagtail.fields.StreamField([('table', wagtail.contrib.table_block.blocks.TableBlock(table_options={'autoColumnSize': True, 'contextMenu': ['mergeCells', 'row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'undo', 'redo', '---------', 'copy', 'cut---------', 'alignment'], 'mergeCells': True}))], blank=True, null=True, use_json_field=True),
        ),
    ]
