export const players = [
  {
    id: "1",
    player_nickname: "ZywOo",
    game: "csgo",
    slug: "zywoo",
    player_full_name: " Mathieu Herbaut",
    player_country: "",
    player_age: "21",
    player_team: "Vitality",
    player_social: { Twitter: "https://www.twitter.com/zywoo", Twitch: "https://www.twitch.tv/cs_zywoo", Instagram: "https://www.instagram.com/cs_zywoo" },
    player_all_trophies_list: [
      { name: "IEM Winter 2021", img: "https://www.hltv.org/img/static/event/trophies/5730.png" },
      { name: "BLAST Premier Fall 2020 Finals", img: "https://img-cdn.hltv.org/eventlogo/7k60AiYcHhC1rCcJGWWUvx.png?ixlib=java-2.1.0&w=50&s=4b9bc9148f3a5dcda189e96e6369fd0d" },
      { name: "IEM Beijing-Haidian 2020 Europe", img: "https://img-cdn.hltv.org/eventlogo/dxrSBtNp6X_5sEX_RtI-9F.png?ixlib=java-2.1.0&w=50&s=4495ad07a9c3477df3ddaab1ca012d0e" },
      { name: "EPICENTER 2019", img: "https://www.hltv.org/img/static/event/trophies/4979.png" },
      { name: "ECS Season 7 Finals", img: "https://www.hltv.org/img/static/event/trophies/4411.png" },
      { name: "cs_summit 4", img: "https://img-cdn.hltv.org/eventlogo/aEMJ9OlH4Qoh9eWHbUsnyX.png?ixlib=java-2.1.0&w=50&s=3c4fcf9694652242854ea85aec17fe80" },
    ],
    player_all_mvps_list: [
      { name: "IEM Winter 2021", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "BLAST Premier Fall 2020 Finals", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "IEM Beijing-Haidian 2020 Europe", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "DreamHack Open Fall 2020", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "ESL One Cologne 2020 Europe", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "cs_summit 6 Europe", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "BLAST Premier Spring 2020 Europe Finals", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "EPICENTER 2019", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "DreamHack Masters Malm\u00f6 2019", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "ESL One Cologne 2019", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "ECS Season 7 Finals", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "cs_summit 4", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
    ],
    player_all_top20_list: [
      { name: "#2 best player in 21", img: "https://www.hltv.org/img/static/event/trophies/2021/2.png", year: "2021" },
      { name: "#1 best player in 20", img: "https://www.hltv.org/img/static/event/trophies/2020/1.png", year: "2020" },
      { name: "#1 best player in 19", img: "https://www.hltv.org/img/static/event/trophies/2019/1.png", year: "2019" },
    ],
    player_majors_won: "0",
    player_majors_played: "4",
    player_all_majors_list: [
      { placement: "Group stage", team: "Vitality", tournament: "PGL Major Antwerp 2022" },
      { placement: "1/4 final", team: "Vitality", tournament: "PGL Major Stockholm 2021" },
      { placement: "1/4 final", team: "Vitality", tournament: "StarLadder Major Berlin 2019" },
      { placement: "Group stage", team: "Vitality", tournament: "IEM Katowice 2019" },
    ],
    player_lan_won: "4",
    player_lan_played: "24",
    player_all_lan_list: [
      { placement: "2nd", team: "Vitality", tournament: "BLAST Premier Spring Final 2022" },
      { placement: "3rd", team: "Vitality", tournament: "BLAST Premier World Final 2021" },
      { placement: "1st", team: "Vitality", tournament: "IEM Winter 2021" },
      { placement: "2nd", team: "Vitality", tournament: "BLAST Premier Fall Final 2021" },
      { placement: "1st", team: "Vitality", tournament: "EPICENTER 2019" },
      { placement: "3-4th", team: "Vitality", tournament: "IEM Beijing 2019" },
      { placement: "2nd", team: "Vitality", tournament: "DreamHack Masters Malm\u00f6 2019" },
      { placement: "3-4th", team: "Vitality", tournament: "IEM Chicago 2019" },
      { placement: "2nd", team: "Vitality", tournament: "ESL One Cologne 2019" },
      { placement: "1st", team: "Vitality", tournament: "ECS Season 7 Finals" },
      { placement: "1st", team: "Vitality", tournament: "cs_summit 4" },
    ],
    player_all_teams_list: [
      {
        time: "Oct 2018 - Present",
        team_name: "Vitality",
        trophies: [
          { title: "IEM Winter 2021", img: "https://www.hltv.org/img/static/event/trophies/5730.png" },
          { title: "BLAST Premier Fall 2020 Finals", img: "https://img-cdn.hltv.org/eventlogo/7k60AiYcHhC1rCcJGWWUvx.png?ixlib=java-2.1.0&w=50&s=4b9bc9148f3a5dcda189e96e6369fd0d" },
          { title: "IEM Beijing-Haidian 2020 Europe", img: "https://img-cdn.hltv.org/eventlogo/dxrSBtNp6X_5sEX_RtI-9F.png?ixlib=java-2.1.0&w=50&s=4495ad07a9c3477df3ddaab1ca012d0e" },
          { title: "EPICENTER 2019", img: "https://www.hltv.org/img/static/event/trophies/4979.png" },
          { title: "ECS Season 7 Finals", img: "https://www.hltv.org/img/static/event/trophies/4411.png" },
          { title: "cs_summit 4", img: "https://img-cdn.hltv.org/eventlogo/aEMJ9OlH4Qoh9eWHbUsnyX.png?ixlib=java-2.1.0&w=50&s=3c4fcf9694652242854ea85aec17fe80" },
        ],
      },
      { time: "Sep 2017 - Sep 2018", team_name: "aAa", trophies: [] },
      { time: "Mar 2017 - Aug 2017", team_name: "WySix", trophies: [] },
    ],
  },
  {
    id: "2",
    player_nickname: "s1mple",
    game: "csgo",
    slug: "s1mple",
    player_full_name: " Aleksandr Kostyliev",
    player_country: "",
    player_age: "24",
    player_team: "Natus Vincere",
    player_social: { Twitter: "https://www.twitter.com/s1mpleO", Twitch: "https://www.twitch.tv/s1mple", Instagram: "https://www.instagram.com/s1mpleo" },
    player_all_trophies_list: [
      { name: "BLAST Premier Spring Final 2022", img: "https://img-cdn.hltv.org/eventlogo/O8dyTstiXZp1wPIcOGi_GC.png?ixlib=java-2.1.0&w=50&s=12e9363167f3ca426565ebd59124a88a" },
      { name: "BLAST Premier World Final 2021", img: "https://img-cdn.hltv.org/eventlogo/fPM7FeExkV6ONUjA3SOjGT.png?ixlib=java-2.1.0&w=50&s=aedf03c8c58a97261b120c683768944d" },
      { name: "BLAST Premier Fall Final 2021", img: "https://www.hltv.org/img/static/event/trophies/5607.png" },
      { name: "PGL Major Stockholm 2021", img: "https://www.hltv.org/img/static/event/trophies/4866.png" },
      { name: "Winner of Intel Grand Slam Season 3", img: "https://www.hltv.org/img/static/event/grandSlam.png" },
      { name: "ESL Pro League Season 14", img: "https://www.hltv.org/img/static/event/trophies/5554.png" },
      { name: "IEM Cologne 2021", img: "https://www.hltv.org/img/static/event/trophies/5469.png" },
      { name: "StarLadder CIS RMR 2021", img: "https://img-cdn.hltv.org/eventlogo/bIYhaEw1Y1M2dRFAEx8Mue.png?ixlib=java-2.1.0&w=50&s=bfdfd2e5184d1ca2cbde100720f77821" },
      { name: "DreamHack Masters Spring 2021", img: "https://img-cdn.hltv.org/eventlogo/wZYnxtRyDPfSU3tWsfzbx7.png?ixlib=java-2.1.0&w=50&s=85e8e8904fc1730b1eccac77da15a1ca" },
      { name: "BLAST Premier Global Final 2020", img: "https://img-cdn.hltv.org/eventlogo/fPM7FeExkV6ONUjA3SOjGT.png?ixlib=java-2.1.0&w=50&s=aedf03c8c58a97261b120c683768944d" },
      { name: "IEM Katowice 2020", img: "https://www.hltv.org/img/static/event/trophies/4901.png" },
      { name: "StarSeries i-League Season 7", img: "https://www.hltv.org/img/static/event/trophies/4240.png" },
      { name: "BLAST Pro Series Copenhagen 2018", img: "https://www.hltv.org/img/static/event/trophies/3701.png" },
      { name: "ESL One Cologne 2018", img: "https://www.hltv.org/img/static/event/trophies/3392.png" },
      { name: "CS:GO Asia Championships 2018", img: "https://www.hltv.org/img/static/event/trophies/3714.png" },
      { name: "StarSeries i-League Season 5", img: "https://www.hltv.org/img/static/event/trophies/3666.png" },
      { name: "DreamHack Open Winter 2017", img: "https://www.hltv.org/img/static/event/trophies/2574.png" },
      { name: "ESL One New York 2016", img: "https://www.hltv.org/img/static/event/trophies/2239.png" },
    ],
    player_all_mvps_list: [
      { name: "IEM Cologne 2022", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "BLAST Premier Spring Final 2022", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "BLAST Premier World Final 2021", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "BLAST Premier Fall Final 2021", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "PGL Major Stockholm 2021", img: "https://www.hltv.org/img/static/event/mvpGold.png" },
      { name: "ESL Pro League Season 14", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "IEM Cologne 2021", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "StarLadder CIS RMR 2021", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "DreamHack Masters Spring 2021", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "BLAST Premier Global Final 2020", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "ESL Pro League Season 12 Europe", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "IEM Katowice 2020", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "StarSeries i-League Season 7", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "BLAST Pro Series Copenhagen 2018", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "ESL One Cologne 2018", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "CS:GO Asia Championships 2018", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "StarSeries i-League Season 5", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "DreamHack Masters Marseille 2018", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "StarSeries i-League Season 4", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "DreamHack Open Winter 2017", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "ESL One New York 2016", img: "https://www.hltv.org/img/static/event/mvpOld.png" },
    ],
    player_all_top20_list: [
      { name: "#1 best player in 21", img: "https://www.hltv.org/img/static/event/trophies/2021/1.png", year: "2021" },
      { name: "#2 best player in 20", img: "https://www.hltv.org/img/static/event/trophies/2020/2.png", year: "2020" },
      { name: "#2 best player in 19", img: "https://www.hltv.org/img/static/event/trophies/2019/2.png", year: "2019" },
      { name: "#1 best player in 18", img: "https://www.hltv.org/img/static/event/trophies/2018/1.png", year: "2018" },
      { name: "#8 best player in 17", img: "https://www.hltv.org/img/static/event/trophies/2017/8.png", year: "2017" },
      { name: "#4 best player in 16", img: "https://www.hltv.org/img/static/event/trophies/2016/4.png", year: "2016" },
    ],
    player_majors_won: "1",
    player_majors_played: "11",
    player_all_majors_list: [
      { placement: "2nd", team: "Natus Vincere", tournament: "PGL Major Antwerp 2022" },
      { placement: "1st", team: "Natus Vincere", tournament: "PGL Major Stockholm 2021" },
      { placement: "1/4 final", team: "Natus Vincere", tournament: "StarLadder Major Berlin 2019" },
      { placement: "3-4th", team: "Natus Vincere", tournament: "IEM Katowice 2019" },
      { placement: "2nd", team: "Natus Vincere", tournament: "FACEIT Major 2018" },
      { placement: "3-4th", team: "Natus Vincere", tournament: "ELEAGUE Major 2018" },
      { placement: "Group stage", team: "Natus Vincere", tournament: "PGL Major Krakow 2017" },
      { placement: "1/4 final", team: "Natus Vincere", tournament: "ELEAGUE Major 2017" },
      { placement: "2nd", team: "Liquid", tournament: "ESL One Cologne 2016" },
      { placement: "3-4th", team: "Liquid", tournament: "MLG Columbus 2016" },
      { placement: "1/4 final", team: "HellRaisers", tournament: "DreamHack Winter 2014" },
    ],
    player_lan_won: "13",
    player_lan_played: "69",
    player_all_lan_list: [
      { placement: "2nd", team: "Natus Vincere", tournament: "IEM Cologne 2022" },
      { placement: "1st", team: "Natus Vincere", tournament: "BLAST Premier Spring Final 2022" },
      { placement: "2nd", team: "Natus Vincere", tournament: "PGL Major Antwerp 2022" },
      { placement: "3-4th", team: "Natus Vincere", tournament: "IEM Katowice 2022" },
      { placement: "1st", team: "Natus Vincere", tournament: "BLAST Premier World Final 2021" },
      { placement: "1st", team: "Natus Vincere", tournament: "BLAST Premier Fall Final 2021" },
      { placement: "1st", team: "Natus Vincere", tournament: "PGL Major Stockholm 2021" },
      { placement: "1st", team: "Natus Vincere", tournament: "IEM Cologne 2021" },
      { placement: "1st", team: "Natus Vincere", tournament: "IEM Katowice 2020" },
      { placement: "2nd", team: "Natus Vincere", tournament: "ICE Challenge 2020" },
      { placement: "3-4th", team: "Natus Vincere", tournament: "ESL Pro League Season 10 Finals" },
      { placement: "3rd", team: "Natus Vincere", tournament: "BLAST Pro Series Copenhagen 2019" },
      { placement: "3-4th", team: "Natus Vincere", tournament: "DreamHack Masters Malm\u00f6 2019" },
      { placement: "3-4th", team: "Natus Vincere", tournament: "ESL One Cologne 2019" },
      { placement: "1st", team: "Natus Vincere", tournament: "StarSeries i-League Season 7" },
      { placement: "3-4th", team: "Natus Vincere", tournament: "IEM Katowice 2019" },
      { placement: "2nd", team: "Natus Vincere", tournament: "BLAST Pro Series Lisbon 2018" },
      { placement: "1st", team: "Natus Vincere", tournament: "BLAST Pro Series Copenhagen 2018" },
      { placement: "2nd", team: "Natus Vincere", tournament: "EPICENTER 2018" },
      { placement: "2nd", team: "Natus Vincere", tournament: "FACEIT Major 2018" },
      { placement: "3-4th", team: "Natus Vincere", tournament: "ELEAGUE CS:GO Premier 2018" },
      { placement: "1st", team: "Natus Vincere", tournament: "ESL One Cologne 2018" },
      { placement: "1st", team: "Natus Vincere", tournament: "CS:GO Asia Championships 2018" },
      { placement: "1st", team: "Natus Vincere", tournament: "StarSeries i-League Season 5" },
      { placement: "3-4th", team: "Natus Vincere", tournament: "ESL Pro League Season 7 Finals" },
      { placement: "2nd", team: "Natus Vincere", tournament: "DreamHack Masters Marseille 2018" },
      { placement: "2nd", team: "Natus Vincere", tournament: "StarSeries i-League Season 4" },
      { placement: "3-4th", team: "Natus Vincere", tournament: "ELEAGUE Major 2018" },
      { placement: "1st", team: "Natus Vincere", tournament: "DreamHack Open Winter 2017" },
      { placement: "3-4th", team: "Natus Vincere", tournament: "ESL One Cologne 2017" },
      { placement: "3-4th", team: "Natus Vincere", tournament: "SL i-League StarSeries Season 3 Finals" },
      { placement: "3-4th", team: "Natus Vincere", tournament: "EPICENTER: Moscow" },
      { placement: "1st", team: "Natus Vincere", tournament: "ESL One New York 2016" },
      { placement: "2nd", team: "Liquid", tournament: "ESL One Cologne 2016" },
      { placement: "3-4th", team: "Liquid", tournament: "MLG Columbus 2016" },
      { placement: "3-4th", team: "FlipSid3", tournament: "ESWC 2015" },
      { placement: "3-4th", team: "FlipSid3", tournament: "SLTV StarSeries XIII Finals" },
      { placement: "2nd", team: "HellRaisers", tournament: "Game Show Season 1 Finals" },
    ],
    player_all_teams_list: [
      {
        time: "Aug 2016 - Present",
        team_name: "Natus Vincere",
        trophies: [
          { title: "BLAST Premier Spring Final 2022", img: "https://img-cdn.hltv.org/eventlogo/O8dyTstiXZp1wPIcOGi_GC.png?ixlib=java-2.1.0&w=50&s=12e9363167f3ca426565ebd59124a88a" },
          { title: "BLAST Premier World Final 2021", img: "https://img-cdn.hltv.org/eventlogo/fPM7FeExkV6ONUjA3SOjGT.png?ixlib=java-2.1.0&w=50&s=aedf03c8c58a97261b120c683768944d" },
          { title: "BLAST Premier Fall Final 2021", img: "https://www.hltv.org/img/static/event/trophies/5607.png" },
          { title: "PGL Major Stockholm 2021", img: "https://www.hltv.org/img/static/event/trophies/4866.png" },
          { title: "Winner of Intel Grand Slam Season 3", img: "https://www.hltv.org/img/static/event/grandSlam.png" },
          { title: "ESL Pro League Season 14", img: "https://www.hltv.org/img/static/event/trophies/5554.png" },
          { title: "IEM Cologne 2021", img: "https://www.hltv.org/img/static/event/trophies/5469.png" },
          { title: "StarLadder CIS RMR 2021", img: "https://img-cdn.hltv.org/eventlogo/bIYhaEw1Y1M2dRFAEx8Mue.png?ixlib=java-2.1.0&w=50&s=bfdfd2e5184d1ca2cbde100720f77821" },
          { title: "DreamHack Masters Spring 2021", img: "https://img-cdn.hltv.org/eventlogo/wZYnxtRyDPfSU3tWsfzbx7.png?ixlib=java-2.1.0&w=50&s=85e8e8904fc1730b1eccac77da15a1ca" },
          { title: "BLAST Premier Global Final 2020", img: "https://img-cdn.hltv.org/eventlogo/fPM7FeExkV6ONUjA3SOjGT.png?ixlib=java-2.1.0&w=50&s=aedf03c8c58a97261b120c683768944d" },
          { title: "IEM Katowice 2020", img: "https://www.hltv.org/img/static/event/trophies/4901.png" },
          { title: "StarSeries i-League Season 7", img: "https://www.hltv.org/img/static/event/trophies/4240.png" },
          { title: "BLAST Pro Series Copenhagen 2018", img: "https://www.hltv.org/img/static/event/trophies/3701.png" },
          { title: "ESL One Cologne 2018", img: "https://www.hltv.org/img/static/event/trophies/3392.png" },
          { title: "CS:GO Asia Championships 2018", img: "https://www.hltv.org/img/static/event/trophies/3714.png" },
          { title: "StarSeries i-League Season 5", img: "https://www.hltv.org/img/static/event/trophies/3666.png" },
          { title: "DreamHack Open Winter 2017", img: "https://www.hltv.org/img/static/event/trophies/2574.png" },
          { title: "ESL One New York 2016", img: "https://www.hltv.org/img/static/event/trophies/2239.png" },
        ],
      },
      { time: "Feb 2016 - Apr 2016", team_name: "Liquid", trophies: [] },
      { time: "Sep 2015 - Nov 2015", team_name: "HellRaisers", trophies: [] },
      { time: "Mar 2015 - Jul 2015", team_name: "FlipSid3", trophies: [] },
      { time: "Sep 2014 - Jan 2015", team_name: "HellRaisers", trophies: [] },
    ],
  },
  {
    id: "3",
    player_nickname: "sh1ro",
    game: "csgo",
    slug: "sh1ro",
    player_full_name: " Dmitry Sokolov",
    player_country: "",
    player_age: "21",
    player_team: "Cloud9",
    player_social: { Twitter: "https://www.twitter.com/sh1rocsgo", Twitch: "https://www.twitch.tv/sh1ro1769" },
    player_all_trophies_list: [
      { name: "IEM Dallas 2022", img: "https://www.hltv.org/img/static/event/trophies/6138.png" },
      { name: "Funspark ULTI 2021 Finals", img: "https://img-cdn.hltv.org/eventlogo/eZuADJhebwE9L3-2jJV-wH.png?ixlib=java-2.1.0&w=50&s=9ed7d095e3bc2fd841ddfc92bcc56123" },
      { name: "V4 Future Sports Festival 2021", img: "https://www.hltv.org/img/static/event/trophies/6018.png" },
      { name: "IEM Fall 2021 CIS", img: "https://img-cdn.hltv.org/eventlogo/-tCAE4lhriejiElcDnJPWG.png?ixlib=java-2.1.0&w=50&s=d10fab26b4b42ac57c837ae2dbdc2cb9" },
      { name: "BLAST Premier Spring Final 2021", img: "https://img-cdn.hltv.org/eventlogo/7k60AiYcHhC1rCcJGWWUvx.png?ixlib=java-2.1.0&w=50&s=4b9bc9148f3a5dcda189e96e6369fd0d" },
      { name: "IEM Summer 2021", img: "https://img-cdn.hltv.org/eventlogo/0wBIe8cq-8bsTFP6M-tDPf.png?ixlib=java-2.1.0&w=50&s=5fa9e94d200fce7332a72b19dfb72e73" },
      { name: "EPIC League CIS 2021", img: "https://img-cdn.hltv.org/eventlogo/wclZ0x4gdk14vlBvxIMNsH.png?ixlib=java-2.1.0&w=50&s=712401f063d9b37fff24885a0e6fa62c" },
      { name: "IEM Katowice 2021", img: "https://img-cdn.hltv.org/eventlogo/jr37oyawVOwSLCKdXmh8rr.png?ixlib=java-2.1.0&w=50&s=0d06b621779b44bcf858f747275050ba" },
    ],
    player_all_mvps_list: [
      { name: "Funspark ULTI 2021 Finals", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "V4 Future Sports Festival 2021", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "IEM Fall 2021 CIS", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
      { name: "IEM Katowice 2021", img: "https://www.hltv.org/img/static/event/mvpSilver.png" },
    ],
    player_all_top20_list: [{ name: "#4 best player in 21", img: "https://www.hltv.org/img/static/event/trophies/2021/4.png", year: "2021" }],
    player_majors_won: "0",
    player_majors_played: "2",
    player_all_majors_list: [
      { placement: "Group stage", team: "Cloud9", tournament: "PGL Major Antwerp 2022" },
      { placement: "3-4th", team: "Gambit", tournament: "PGL Major Stockholm 2021" },
    ],
    player_lan_won: "1",
    player_lan_played: "9",
    player_all_lan_list: [
      { placement: "1st", team: "Cloud9", tournament: "IEM Dallas 2022" },
      { placement: "2nd", team: "Gambit", tournament: "BLAST Premier World Final 2021" },
      { placement: "3-4th", team: "Gambit", tournament: "PGL Major Stockholm 2021" },
    ],
    player_all_teams_list: [
      { time: "Apr 2022 - Present", team_name: "Cloud9", trophies: [{ title: "IEM Dallas 2022", img: "https://www.hltv.org/img/static/event/trophies/6138.png" }] },
      { time: "Mar 2022 - Apr 2022", team_name: "Players", trophies: [] },
      {
        time: "Oct 2020 - Mar 2022",
        team_name: "Gambit",
        trophies: [
          { title: "Funspark ULTI 2021 Finals", img: "https://img-cdn.hltv.org/eventlogo/eZuADJhebwE9L3-2jJV-wH.png?ixlib=java-2.1.0&w=50&s=9ed7d095e3bc2fd841ddfc92bcc56123" },
          { title: "V4 Future Sports Festival 2021", img: "https://www.hltv.org/img/static/event/trophies/6018.png" },
          { title: "IEM Fall 2021 CIS", img: "https://img-cdn.hltv.org/eventlogo/-tCAE4lhriejiElcDnJPWG.png?ixlib=java-2.1.0&w=50&s=d10fab26b4b42ac57c837ae2dbdc2cb9" },
          { title: "BLAST Premier Spring Final 2021", img: "https://img-cdn.hltv.org/eventlogo/7k60AiYcHhC1rCcJGWWUvx.png?ixlib=java-2.1.0&w=50&s=4b9bc9148f3a5dcda189e96e6369fd0d" },
          { title: "IEM Summer 2021", img: "https://img-cdn.hltv.org/eventlogo/0wBIe8cq-8bsTFP6M-tDPf.png?ixlib=java-2.1.0&w=50&s=5fa9e94d200fce7332a72b19dfb72e73" },
          { title: "EPIC League CIS 2021", img: "https://img-cdn.hltv.org/eventlogo/wclZ0x4gdk14vlBvxIMNsH.png?ixlib=java-2.1.0&w=50&s=712401f063d9b37fff24885a0e6fa62c" },
          { title: "IEM Katowice 2021", img: "https://img-cdn.hltv.org/eventlogo/jr37oyawVOwSLCKdXmh8rr.png?ixlib=java-2.1.0&w=50&s=0d06b621779b44bcf858f747275050ba" },
        ],
      },
      { time: "Apr 2019 - Sep 2020", team_name: "Gambit Youngsters", trophies: [] },
      { time: "Sep 2018 - Nov 2018", team_name: "Vyalie Pitoni", trophies: [] },
    ],
  },
  {
    id: "4",
    player_nickname: "deko",
    game: "valorant",
    slug: "deko",
    player_full_name: " Denis Zhukov",
    player_country: "",
    player_age: "21",
    player_team: "1WIN",
    player_social: { Instagram: "https://www.instagram.com/dekocsoff" },
    player_all_trophies_list: [],
    player_all_mvps_list: [],
    player_all_top20_list: [],
    player_majors_won: "0",
    player_majors_played: "2",
    player_all_majors_list: [],
    player_lan_won: "1",
    player_lan_played: "9",
    player_all_lan_list: [],
    player_all_teams_list: [{ time: "Dec 2020 - Present", team_name: "1WIN", trophies: [] }],
  },
  {
    id: "5",
    player_nickname: "saffee",
    game: "csgo",
    slug: "saffee",
    player_full_name: " Rafael Costa",
    player_country: "",
    player_age: "27",
    player_team: "FURIA",
    player_social: { Twitter: "https://www.twitter.com/saffeecsgo", Instagram: "https://www.instagram.com/saffeecsgo" },
    player_all_trophies_list: [],
    player_all_mvps_list: [],
    player_all_top20_list: [],
    player_majors_won: "0",
    player_majors_played: "1",
    player_all_majors_list: [{ placement: "1/4 final", team: "FURIA", tournament: "PGL Major Antwerp 2022" }],
    player_lan_won: "0",
    player_lan_played: "5",
    player_all_lan_list: [
      { placement: "3-4th", team: "FURIA", tournament: "IEM Dallas 2022" },
      { placement: "3-4th", team: "FURIA", tournament: "ESL Pro League Season 15" },
    ],
    player_all_teams_list: [
      { time: "Jan 2022 - Present", team_name: "FURIA", trophies: [] },
      { time: "Jul 2020 - Jan 2022", team_name: "paiN", trophies: [] },
    ],
  },
  {
    id: "6",
    player_nickname: "Kaze",
    game: "csgo",
    slug: "kaze",
    player_full_name: " Andrew Khong",
    player_country: "",
    player_age: "28",
    player_team: "Rare Atom",
    player_social: { Twitter: "https://www.twitter.com/kaze_cs", Twitch: "https://www.twitch.tv/kaze1" },
    player_all_trophies_list: [],
    player_all_mvps_list: [],
    player_all_top20_list: [],
    player_majors_won: "0",
    player_majors_played: "1",
    player_all_majors_list: [],
    player_lan_won: "0",
    player_lan_played: "5",
    player_all_lan_list: [],
    player_all_teams_list: [
      { time: "Jan 2022 - Present", team_name: "Rare Atom", trophies: [] },
      { time: "Sep 2018 - Jan 2022", team_name: "ViCi", trophies: [] },
      { time: "May 2017 - Mar 2018", team_name: "Flash", trophies: [] },
      { time: "Nov 2016 - Apr 2017", team_name: "JYP", trophies: [] },
      { time: "Oct 2016 - Nov 2016", team_name: "Fire Dragoon", trophies: [] },
      { time: "Apr 2015 - Oct 2016", team_name: "MVP.karnal", trophies: [] },
    ],
  },
];

export const games = [
  {
    id: "1",
    title: "Counter-Strike: Global Offensive",
    slug: "csgo",
    abbr: "CS:GO",
  },
  {
    id: "2",
    title: "VALORANT",
    slug: "valorant",
    abbr: "",
  },
  {
    id: "3",
    title: "Dota 2",
    slug: "dota2",
    abbr: "DOTA2",
  },
  {
    id: "4",
    title: "League of Legends",
    slug: "lol",
    abbr: "LoL",
  },
  {
    id: "5",
    title: "Overwatch",
    slug: "overwatch",
    abbr: "",
  },
  {
    id: "6",
    title: "Apex Legends",
    slug: "apex",
    abbr: "Apex",
  },
  {
    id: "7",
    title: "Fortnite",
    slug: "fortnite",
    abbr: "",
  },
  {
    id: "8",
    title: "PlayerUnknown's Battlegrounds",
    slug: "pubg",
    abbr: "PUBG",
  },
  {
    id: "9",
    title: "Halo",
    slug: "halo",
    abbr: "",
  },
  {
    id: "10",
    title: "Rainbow Six Siege",
    slug: "rsi",
    abbr: "",
  },
];

export const teams = [
  {
    id: "1",
    title: "Natus Vincere",
    slug: "navi",
    game: "csgo",
  },
  {
    id: "2",
    title: "FURIA",
    slug: "furia",
    game: "csgo",
  },
  {
    id: "3",
    title: "paiN",
    slug: "pain",
    game: "csgo",
  },
  {
    id: "4",
    title: "ViCi",
    slug: "vici",
    game: "csgo",
  },
  {
    id: "5",
    title: "Flash",
    slug: "flash",
    game: "valorant",
  },
  {
    id: "6",
    title: "FaZe Clan",
    slug: "faze",
    game: "csgo",
  },
];
