# Generated by Django 4.0.6 on 2022-07-15 18:22

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('news', '0004_newstagindexpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name_plural': 'news categories',
            },
        ),
        migrations.RemoveField(
            model_name='newstagindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='tags',
        ),
        migrations.DeleteModel(
            name='NewsPageTag',
        ),
        migrations.DeleteModel(
            name='NewsTagIndexPage',
        ),
        migrations.AddField(
            model_name='newspage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, null=True, to='news.newscategory'),
        ),
    ]
