# Generated by Django 4.0.6 on 2022-07-15 18:22

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newscategory_remove_newstagindexpage_page_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='news.newscategory'),
        ),
    ]
