# Generated by Django 4.0.6 on 2022-07-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_newspage_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
