# Generated by Django 4.0.6 on 2022-07-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_newspagetag_newstagindexpage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsTagIndexPage',
        ),
    ]
