# Generated by Django 4.0.6 on 2022-07-17 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_delete_newstagindexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='tags',
        ),
        migrations.DeleteModel(
            name='NewsPageTag',
        ),
    ]
