# Generated by Django 4.0.6 on 2022-07-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_newscats_newspage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscats',
            name='bol',
            field=models.BooleanField(default=False),
        ),
    ]
