# Generated by Django 4.0.6 on 2022-07-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_newscats_bol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscats',
            name='bol',
            field=models.BooleanField(default=True),
        ),
    ]
