# Generated by Django 4.0.6 on 2022-07-19 12:07

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('profiles', '0019_remove_newsindexpage_page_ptr_and_more'),
        ('news', '0015_remove_newspage_bol_remove_newspage_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='game',
        ),
        migrations.AddField(
            model_name='newspage',
            name='game',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='game_news', to='wagtailcore.page'),
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='player',
        ),
        migrations.AddField(
            model_name='newspage',
            name='player',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='player_news', to='profiles.profilepage'),
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='team',
        ),
        migrations.AddField(
            model_name='newspage',
            name='team',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='+', to='profiles.teampage'),
        ),
    ]
