# Generated by Django 4.0.6 on 2022-07-19 12:10

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('news', '0016_remove_newspage_game_newspage_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='game',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='player',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='team',
        ),
        migrations.AddField(
            model_name='newspage',
            name='tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='+', to='wagtailcore.page'),
        ),
    ]
