# Generated by Django 4.0.6 on 2022-07-19 14:10

from django.db import migrations
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_remove_newspage_game_remove_newspage_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='text',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True, use_json_field=True),
        ),
    ]
