# Generated by Django 4.0.6 on 2022-07-19 17:39

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('news', '0019_alter_newspage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='news_tags', to='wagtailcore.page'),
        ),
    ]
