# Generated by Django 4.0.3 on 2022-04-06 21:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PcSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(max_length=70)),
                ('meta_description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('publish', models.BooleanField(default=False)),
                ('specs_type', models.CharField(choices=[('mon', 'Monitor'), ('ms', 'Mouse'), ('msp', 'Mousepad'), ('key', 'Keyboard'), ('hs', 'Headset'), ('cpu', 'CPU'), ('gpu', 'GPU'), ('mb', 'Motherboard'), ('ram', 'RAM'), ('case', 'Case/Tower'), ('hdd', 'HDD'), ('ssd', 'SSD'), ('ps', 'Power Supply'), ('mic', 'Microphone'), ('cam', 'Camera'), ('wcam', 'Webcam'), ('ch', 'Chair'), ('lc', 'Liquid Cooling'), ('fn', 'Fans'), ('arm', 'ARM'), ('sl', 'Studio Light'), ('con', 'Controller'), ('o', 'Other')], default='o', max_length=4)),
                ('amazon_url', models.URLField()),
                ('reviews', models.TextField(blank=True)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to='core.imagecollection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='newscategory',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wiki',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wikicategory',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SetupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(max_length=70)),
                ('meta_description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('publish', models.BooleanField(default=False)),
                ('overview', models.TextField(blank=True)),
                ('settings_body', models.TextField(blank=True)),
                ('settings', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=None)),
                ('setup_body', models.TextField(blank=True)),
                ('ref', models.TextField(blank=True)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to='core.imagecollection')),
                ('specs', models.ManyToManyField(related_name='person_specs', to='core.pcspecs')),
                ('tags', models.ManyToManyField(related_name='things_linked', to='core.wiki')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(max_length=70)),
                ('meta_description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('publish', models.BooleanField(default=False)),
                ('overview', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('ref', models.TextField(blank=True)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to='core.imagecollection')),
                ('tags', models.ManyToManyField(related_name='news_tags', to='core.newscategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
