# Generated by Django 4.0.4 on 2022-06-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamprofile',
            old_name='active_players',
            new_name='active_members',
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='former_members',
            field=models.ManyToManyField(related_name='former_roster', to='core.wiki'),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='inactive_members',
            field=models.ManyToManyField(related_name='inactive_roster', to='core.wiki'),
        ),
    ]
