# Generated by Django 4.0.4 on 2022-06-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_active_players_teamprofile_active_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamprofile',
            name='active_members',
            field=models.ManyToManyField(blank=True, related_name='active_roster', to='core.wiki'),
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='former_members',
            field=models.ManyToManyField(blank=True, related_name='former_roster', to='core.wiki'),
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='inactive_members',
            field=models.ManyToManyField(blank=True, related_name='inactive_roster', to='core.wiki'),
        ),
    ]
