# Generated by Django 4.0.3 on 2022-04-06 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pcspecs_newscategory_publish_topic_publish_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagecollection',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name': 'News Category', 'verbose_name_plural': 'News Categories'},
        ),
        migrations.AlterModelOptions(
            name='pcspecs',
            options={'verbose_name': 'PC Specs', 'verbose_name_plural': 'PC Specs'},
        ),
        migrations.AlterModelOptions(
            name='setupsettings',
            options={'verbose_name': 'Setup and Settings', 'verbose_name_plural': 'Setup and Settings'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AlterModelOptions(
            name='wiki',
            options={'verbose_name': 'Wiki', 'verbose_name_plural': 'Wikis'},
        ),
        migrations.AlterModelOptions(
            name='wikicategory',
            options={'verbose_name': 'Wiki Category', 'verbose_name_plural': 'Wiki Categories'},
        ),
    ]
