# Generated by Django 4.0.3 on 2022-04-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pcspecs_section_alter_imagecollection_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcspecs',
            name='specs_type',
            field=models.CharField(choices=[('mon', 'Monitor'), ('ms', 'Mouse'), ('msp', 'Mousepad'), ('key', 'Keyboard'), ('hs', 'Headset'), ('cpu', 'CPU'), ('gpu', 'GPU'), ('mb', 'Motherboard'), ('ram', 'RAM'), ('case', 'Case/Tower'), ('hdd', 'HDD'), ('ssd', 'SSD'), ('ps', 'Power Supply'), ('mic', 'Microphone'), ('cam', 'Camera'), ('wcam', 'Webcam'), ('ch', 'Chair'), ('lc', 'Liquid Cooling'), ('fn', 'Fans'), ('arm', 'ARM'), ('sl', 'Studio Light'), ('con', 'Controller'), ('o', 'Other')], default='o', max_length=10),
        ),
    ]
