# Generated by Django 4.0.4 on 2022-06-05 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('index_page', models.BooleanField(default=True)),
                ('publish', models.BooleanField(default=False)),
                ('total_maps', models.PositiveIntegerField()),
                ('total_rounds', models.PositiveIntegerField()),
                ('kd', models.PositiveIntegerField()),
                ('kd_diff', models.PositiveIntegerField()),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to='core.imagecollection')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='name_tag', to='core.wiki')),
                ('stats_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stats_tag', to='core.topic')),
            ],
            options={
                'verbose_name': 'Stats',
                'verbose_name_plural': 'Stats',
            },
        ),
    ]
