# Generated by Django 4.0.4 on 2022-06-08 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_teamprofile_active_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupsettings',
            name='related',
            field=models.ManyToManyField(blank=True, null=True, to='core.setupsettings'),
        ),
        migrations.AlterField(
            model_name='setupsettings',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_game', to='core.gameprofile'),
        ),
        migrations.AlterField(
            model_name='setupsettings',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_team', to='core.teamprofile'),
        ),
    ]
