# Generated by Django 4.0.3 on 2022-04-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pcspecs_specs_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupsettings',
            name='specs',
            field=models.ManyToManyField(blank=True, related_name='person_specs', to='core.pcspecs'),
        ),
    ]
