# Generated by Django 4.0.4 on 2022-05-19 10:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_author_news_writer_wiki_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='overview',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
