# Generated by Django 4.0.4 on 2022-06-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_setupsettings_related_alter_setupsettings_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupsettings',
            name='related',
            field=models.ManyToManyField(blank=True, to='core.setupsettings'),
        ),
    ]
