# Generated by Django 4.0.4 on 2022-06-06 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_team_delete_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_name', to='core.game'),
        ),
    ]
