# Generated by Django 4.0.4 on 2022-06-08 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_setupsettings_related'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
