# Generated by Django 4.0.4 on 2022-05-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_wiki_body_alter_wiki_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setupsettings',
            name='team',
        ),
    ]
