# Generated by Django 4.0.3 on 2022-04-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_setupsettings_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondata',
            name='data_type',
            field=models.CharField(choices=[('I', 'Wiki Info'), ('S', 'Player Settings')], default='S', max_length=1),
        ),
    ]
