# Generated by Django 4.0.4 on 2022-06-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupsettings',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
