# Generated by Django 4.0.4 on 2022-06-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_team_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='game',
            new_name='game_wiki',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team',
            new_name='team_wiki',
        ),
    ]
