# Generated by Django 4.0.4 on 2022-05-25 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_setupsettings_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setupsettings',
            name='game',
        ),
    ]
