# Generated by Django 4.0.3 on 2022-04-11 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_jsondata_data_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setupsettings',
            name='tags',
        ),
        migrations.AddField(
            model_name='setupsettings',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_team', to='core.wiki'),
        ),
    ]
