# Generated by Django 4.0.4 on 2022-06-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_game_team_game_wiki_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='TeamSection',
        ),
    ]
