# Generated by Django 4.0.3 on 2022-04-11 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_setupsettings_tags_setupsettings_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki',
            name='page_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wiki_topic', to='core.topic'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='wiki_tags', to='core.wikicategory'),
        ),
    ]
