# Generated by Django 4.0.4 on 2022-05-25 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_setupsettings_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupsettings',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_game', to='core.wiki'),
        ),
        migrations.AddField(
            model_name='setupsettings',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_team', to='core.wiki'),
        ),
    ]
