# Generated by Django 4.0.4 on 2022-06-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_setupsettings_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprofile',
            name='new_slug',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
