# Generated by Django 4.0.3 on 2022-04-11 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_wiki_page_type_alter_wiki_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupsettings',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_game', to='core.wiki'),
        ),
    ]
