# Generated by Django 4.0.3 on 2022-04-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_setupsettings_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='pcspecs',
            name='slug',
            field=models.SlugField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='setupsettings',
            name='slug',
            field=models.SlugField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='slug',
            field=models.SlugField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='wikicategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=80),
        ),
    ]
