# Generated by Django 4.0.4 on 2022-06-09 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_teamprofile_new_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamprofile',
            name='new_slug',
        ),
    ]
