# Generated by Django 4.0.4 on 2022-05-25 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_setupsettings_related'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
    ]
