# Generated by Django 4.0.3 on 2022-04-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_news_slug_alter_newscategory_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupsettings',
            name='is_pro',
            field=models.BooleanField(default=True),
        ),
    ]
