# Generated by Django 4.0.4 on 2022-05-25 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_news_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_tags', to='core.newscategory'),
        ),
    ]
