# Generated by Django 4.0.4 on 2022-06-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_teamprofile_new_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
