# Generated by Django 4.0.3 on 2022-04-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_setupsettings_is_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcspecs',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
