# Generated by Django 4.0.4 on 2022-06-09 23:59

from django.db import migrations
import jsoneditor.fields.django3_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_news_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='images',
            field=jsoneditor.fields.django3_jsonfield.JSONField(blank=True, null=True),
        ),
    ]
