# Generated by Django 4.0.4 on 2022-06-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_news_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupsettings',
            name='team_url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
