# Generated by Django 4.0.4 on 2022-06-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_setupsettings_team_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprofile',
            name='image_url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
