# Generated by Django 4.0.4 on 2022-06-02 07:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_wiki_related'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wiki',
            old_name='body',
            new_name='history',
        ),
        migrations.AddField(
            model_name='wiki',
            name='achievements',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wiki',
            name='career',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wiki',
            name='controversies',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wiki',
            name='team_history',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
