# Generated by Django 4.0.4 on 2022-06-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_body_wiki_history_wiki_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='full_name',
            field=models.CharField(blank=True, help_text='For team and game, use small name like Na’Vi and CS:GO', max_length=50, null=True),
        ),
    ]
