# Generated by Django 4.0.4 on 2022-06-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_wiki_ref_alter_wikicategory_cat_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollection',
            name='image_type',
            field=models.CharField(choices=[('N', 'News'), ('S', 'PcSpecs'), ('P', 'Profile'), ('C', 'Category'), ('I', 'Icon')], max_length=1),
        ),
    ]
