# Generated by Django 4.0.4 on 2022-06-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_imagecollection_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrytag',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='portaltag',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='regiontag',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
