# Generated by Django 4.0.4 on 2022-07-06 07:25

from django.db import migrations, models
import jsoneditor.fields.django3_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_countrytag_slug_alter_portaltag_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('navigation', jsoneditor.fields.django3_jsonfield.JSONField(blank=True)),
            ],
        ),
    ]
