# Generated by Django 4.0.4 on 2022-06-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_wikicategory_cat_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupsettings',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='setup_tags', to='core.wikicategory'),
        ),
    ]
