# Generated by Django 4.0.4 on 2022-06-03 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_setupsettings_tags_setupsettings_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setupsettings',
            name='tags',
        ),
    ]
